baseurl: "https://dalo915.github.io"
languageCode: "en-us"
title: "huoxingqiu website"
theme: "xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:

params:
  description: ""云端的个人网站,hugo网站制作,aws云计算,Linux相关""
  footer: "&copy; 2017 -- 2020 "

markup:
  goldmark:
    renderer:
      unsafe: true

 