baseURL = 'https://dalo915.github.io/'
languageCode = 'en-us'
title = 'HuoXingQiu'

[languages.en]
title = "**** Chen"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[languages.en.menu.main]]
identifier = "skills"
name = "Skills"
url = "/skills/"
weight = 30

[[languages.en.menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience/"
weight = 40

[[languages.en.menu.main]]
identifier = "education"
name = "Education"
url = "/education/"
weight = 50

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 60

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 70

[[languages.en.menu.main]]
identifier = "Documents"
name = "Documents"
url = "/documents/"
weight = 80

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
 
